# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: Canyon
    site_url: canyon.local
    
    company_name: BET
    admin_email: svishwamitra@gmail.com
    
    support_name: Support
    support_email: support@test.com

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
